services:
  # nginx
  web:
    build:
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80" # map port on localhost 80 to container 80 port
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
  # php
  app:
    build:
      dockerfile: ./docker/php/8.2/Dockerfile
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html
  # mysql
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: sail
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php      
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
volumes:
  mysqldata:
